package quic

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strings"
	"sync"
	"time"

	quicgo "github.com/quic-go/quic-go"
)

// ProbePrefix marks a relayed stream as a connectivity probe rather than a
// task's tunnel: the stream's "task id" is ProbePrefix + a service name.
//
// A probe is how the coordinator checks that a gateway is reachable and that
// each service it publishes actually answers on the gateway's own machine (the
// gateway dials the local port and reports what happened). It carries no
// customer data and runs before any Noise session, so the relay still never
// decrypts anything and the coordinator never needs a Noise key.
//
// Only the coordinator may originate one: the relay refuses a probe marker on
// a stream an agent opens (see relayStream), so an agent can't use it to ask a
// customer's gateway which ports on its network are open. Real task IDs are
// generated by the coordinator ("tsk_...") and can't collide with the marker.
const ProbePrefix = "probe:"

// ProbeService returns the service name if streamTaskID is a probe marker.
func ProbeService(streamTaskID string) (service string, ok bool) {
	if !strings.HasPrefix(streamTaskID, ProbePrefix) {
		return "", false
	}
	return strings.TrimPrefix(streamTaskID, ProbePrefix), true
}

// ProbeReply is what a gateway answers one probe with.
type ProbeReply struct {
	OK    bool   `json:"ok"`
	Error string `json:"error,omitempty"`
	Ms    int64  `json:"ms"` // how long the gateway's local dial took
}

// WriteProbeReply sends a reply on the stream a probe arrived on.
func WriteProbeReply(w io.Writer, r ProbeReply) error {
	b, err := json.Marshal(r)
	if err != nil {
		return err
	}
	return writeString(w, string(b))
}

func readProbeReply(r io.Reader) (ProbeReply, error) {
	s, err := readString(r)
	if err != nil {
		return ProbeReply{}, err
	}
	var out ProbeReply
	if err := json.Unmarshal([]byte(s), &out); err != nil {
		return ProbeReply{}, fmt.Errorf("malformed probe reply: %w", err)
	}
	return out, nil
}

// ServiceProbe is the result for one published service.
type ServiceProbe struct {
	Name  string
	OK    bool
	Error string
	Ms    int64
	// Answered is false if the gateway never replied at all, which is what a
	// gateway too old to know about probes looks like.
	Answered bool
}

// GatewayProbe is the result of probing one gateway.
type GatewayProbe struct {
	// Connected: the gateway currently holds a relay session.
	Connected bool
	// RTTMs is the smoothed round-trip time to the gateway over that session.
	RTTMs int64
	// Verified: every service got an answer from the gateway, so a per-service
	// verdict means something. False means we could only confirm the gateway is
	// connected (it may be an older build without the probe).
	Verified bool
	Services []ServiceProbe
}

// probeReplyTimeout bounds how long we wait for one service's reply. It must
// exceed the gateway's own local-dial timeout so "no reply" can only mean the
// gateway doesn't speak the probe, never "the dial was merely slow".
const probeReplyTimeout = 4 * time.Second

// ProbeGateway checks that gatewayID is connected and, for each service name,
// asks the gateway to dial it locally and report the result.
func (r *Relay) ProbeGateway(ctx context.Context, gatewayID string, services []string) GatewayProbe {
	r.mu.Lock()
	conn := r.gateways[gatewayID]
	r.mu.Unlock()
	if conn == nil || conn.Context().Err() != nil {
		return GatewayProbe{}
	}

	out := GatewayProbe{
		Connected: true,
		RTTMs:     conn.ConnectionStats().SmoothedRTT.Milliseconds(),
		Services:  make([]ServiceProbe, len(services)),
	}
	var wg sync.WaitGroup
	for i, name := range services {
		wg.Add(1)
		go func(i int, name string) {
			defer wg.Done()
			out.Services[i] = probeOne(ctx, conn, name)
		}(i, name)
	}
	wg.Wait()

	out.Verified = len(out.Services) > 0
	for _, s := range out.Services {
		if !s.Answered {
			out.Verified = false
		}
	}
	return out
}

func probeOne(ctx context.Context, conn *quicgo.Conn, service string) ServiceProbe {
	res := ServiceProbe{Name: service}
	ctx, cancel := context.WithTimeout(ctx, probeReplyTimeout)
	defer cancel()

	stream, err := conn.OpenStreamSync(ctx)
	if err != nil {
		res.Error = "could not reach the gateway"
		return res
	}
	defer stream.CancelRead(0)
	if err := writeGatewayStreamHeader(stream, gatewayStreamHeader{TaskID: ProbePrefix + service}); err != nil {
		res.Error = "could not reach the gateway"
		return res
	}
	if dl, ok := ctx.Deadline(); ok {
		_ = stream.SetReadDeadline(dl)
	}
	reply, err := readProbeReply(stream)
	_ = stream.Close()
	if err != nil {
		res.Error = "the gateway did not answer: it may need updating"
		return res
	}
	res.Answered, res.OK, res.Error, res.Ms = true, reply.OK, reply.Error, reply.Ms
	return res
}
