// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: lazycake/v1/agent.proto

package lazycakev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Capacity
	//	*AgentMessage_CacheDelta
	//	*AgentMessage_Accepted
	//	*AgentMessage_Rejected
	//	*AgentMessage_Started
	//	*AgentMessage_Finished
	//	*AgentMessage_Logs
	//	*AgentMessage_BenchReport
	Body          isAgentMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetBody() isAgentMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetCapacity() *CapacityReport {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Capacity); ok {
			return x.Capacity
		}
	}
	return nil
}

func (x *AgentMessage) GetCacheDelta() *CacheDelta {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_CacheDelta); ok {
			return x.CacheDelta
		}
	}
	return nil
}

func (x *AgentMessage) GetAccepted() *TaskAccepted {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Accepted); ok {
			return x.Accepted
		}
	}
	return nil
}

func (x *AgentMessage) GetRejected() *TaskRejected {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *AgentMessage) GetStarted() *TaskStarted {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *AgentMessage) GetFinished() *TaskFinished {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Finished); ok {
			return x.Finished
		}
	}
	return nil
}

func (x *AgentMessage) GetLogs() *LogBatch {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Logs); ok {
			return x.Logs
		}
	}
	return nil
}

func (x *AgentMessage) GetBenchReport() *BenchReport {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_BenchReport); ok {
			return x.BenchReport
		}
	}
	return nil
}

type isAgentMessage_Body interface {
	isAgentMessage_Body()
}

type AgentMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Capacity struct {
	Capacity *CapacityReport `protobuf:"bytes,3,opt,name=capacity,proto3,oneof"`
}

type AgentMessage_CacheDelta struct {
	CacheDelta *CacheDelta `protobuf:"bytes,4,opt,name=cache_delta,json=cacheDelta,proto3,oneof"`
}

type AgentMessage_Accepted struct {
	Accepted *TaskAccepted `protobuf:"bytes,5,opt,name=accepted,proto3,oneof"`
}

type AgentMessage_Rejected struct {
	Rejected *TaskRejected `protobuf:"bytes,6,opt,name=rejected,proto3,oneof"`
}

type AgentMessage_Started struct {
	Started *TaskStarted `protobuf:"bytes,7,opt,name=started,proto3,oneof"`
}

type AgentMessage_Finished struct {
	Finished *TaskFinished `protobuf:"bytes,8,opt,name=finished,proto3,oneof"`
}

type AgentMessage_Logs struct {
	Logs *LogBatch `protobuf:"bytes,9,opt,name=logs,proto3,oneof"`
}

type AgentMessage_BenchReport struct {
	BenchReport *BenchReport `protobuf:"bytes,10,opt,name=bench_report,json=benchReport,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Body() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Body() {}

func (*AgentMessage_Capacity) isAgentMessage_Body() {}

func (*AgentMessage_CacheDelta) isAgentMessage_Body() {}

func (*AgentMessage_Accepted) isAgentMessage_Body() {}

func (*AgentMessage_Rejected) isAgentMessage_Body() {}

func (*AgentMessage_Started) isAgentMessage_Body() {}

func (*AgentMessage_Finished) isAgentMessage_Body() {}

func (*AgentMessage_Logs) isAgentMessage_Body() {}

func (*AgentMessage_BenchReport) isAgentMessage_Body() {}

// BenchReport carries a freshly-measured internal/agent/bench score to the
// coordinator (IMPLEMENTATION.md task 4.1) - a dedicated message rather
// than folding it into CapacityReport, since CapacityReport's free_cores
// etc. are only ever sent when actually known and an empty/zero
// CapacityReport would otherwise overwrite the scheduler's placement cache
// with "this node has no free capacity."
type BenchReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BenchReport) Reset() {
	*x = BenchReport{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BenchReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BenchReport) ProtoMessage() {}

func (x *BenchReport) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BenchReport.ProtoReflect.Descriptor instead.
func (*BenchReport) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *BenchReport) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type CoordinatorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*CoordinatorMessage_RegisterAck
	//	*CoordinatorMessage_HeartbeatAck
	//	*CoordinatorMessage_Dispatch
	//	*CoordinatorMessage_Cancel
	Body          isCoordinatorMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorMessage) Reset() {
	*x = CoordinatorMessage{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorMessage) ProtoMessage() {}

func (x *CoordinatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorMessage.ProtoReflect.Descriptor instead.
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *CoordinatorMessage) GetBody() isCoordinatorMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CoordinatorMessage) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Body.(*CoordinatorMessage_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Body.(*CoordinatorMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetDispatch() *Dispatch {
	if x != nil {
		if x, ok := x.Body.(*CoordinatorMessage_Dispatch); ok {
			return x.Dispatch
		}
	}
	return nil
}

func (x *CoordinatorMessage) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Body.(*CoordinatorMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isCoordinatorMessage_Body interface {
	isCoordinatorMessage_Body()
}

type CoordinatorMessage_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,1,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type CoordinatorMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,2,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type CoordinatorMessage_Dispatch struct {
	Dispatch *Dispatch `protobuf:"bytes,3,opt,name=dispatch,proto3,oneof"`
}

type CoordinatorMessage_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

func (*CoordinatorMessage_RegisterAck) isCoordinatorMessage_Body() {}

func (*CoordinatorMessage_HeartbeatAck) isCoordinatorMessage_Body() {}

func (*CoordinatorMessage_Dispatch) isCoordinatorMessage_Body() {}

func (*CoordinatorMessage_Cancel) isCoordinatorMessage_Body() {}

type Register struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Token          string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Hostname       string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Arch           string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	CpuFlags       []string               `protobuf:"bytes,4,rep,name=cpu_flags,json=cpuFlags,proto3" json:"cpu_flags,omitempty"`
	Caps           *Capabilities          `protobuf:"bytes,5,opt,name=caps,proto3" json:"caps,omitempty"`
	Offer          *Offer                 `protobuf:"bytes,6,opt,name=offer,proto3" json:"offer,omitempty"`
	BootId         string                 `protobuf:"bytes,7,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	InstanceId     string                 `protobuf:"bytes,8,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Images         []*CachedImage         `protobuf:"bytes,9,rep,name=images,proto3" json:"images,omitempty"`                                          // full reconciliation on connect
	RunningTaskIds []string               `protobuf:"bytes,10,rep,name=running_task_ids,json=runningTaskIds,proto3" json:"running_task_ids,omitempty"` // re-announced on reconnect for adoption
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Register) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Register) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Register) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Register) GetCpuFlags() []string {
	if x != nil {
		return x.CpuFlags
	}
	return nil
}

func (x *Register) GetCaps() *Capabilities {
	if x != nil {
		return x.Caps
	}
	return nil
}

func (x *Register) GetOffer() *Offer {
	if x != nil {
		return x.Offer
	}
	return nil
}

func (x *Register) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *Register) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Register) GetImages() []*CachedImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Register) GetRunningTaskIds() []string {
	if x != nil {
		return x.RunningTaskIds
	}
	return nil
}

type Capabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryLimit   bool                   `protobuf:"varint,1,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	CpuQuota      bool                   `protobuf:"varint,2,opt,name=cpu_quota,json=cpuQuota,proto3" json:"cpu_quota,omitempty"`
	PidsLimit     bool                   `protobuf:"varint,3,opt,name=pids_limit,json=pidsLimit,proto3" json:"pids_limit,omitempty"`
	DiskLimit     bool                   `protobuf:"varint,4,opt,name=disk_limit,json=diskLimit,proto3" json:"disk_limit,omitempty"`
	Gvisor        bool                   `protobuf:"varint,5,opt,name=gvisor,proto3" json:"gvisor,omitempty"`
	SystemdSlice  bool                   `protobuf:"varint,6,opt,name=systemd_slice,json=systemdSlice,proto3" json:"systemd_slice,omitempty"`
	Runtime       string                 `protobuf:"bytes,7,opt,name=runtime,proto3" json:"runtime,omitempty"` // "podman" | "docker"
	CgroupVersion string                 `protobuf:"bytes,8,opt,name=cgroup_version,json=cgroupVersion,proto3" json:"cgroup_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Capabilities) GetMemoryLimit() bool {
	if x != nil {
		return x.MemoryLimit
	}
	return false
}

func (x *Capabilities) GetCpuQuota() bool {
	if x != nil {
		return x.CpuQuota
	}
	return false
}

func (x *Capabilities) GetPidsLimit() bool {
	if x != nil {
		return x.PidsLimit
	}
	return false
}

func (x *Capabilities) GetDiskLimit() bool {
	if x != nil {
		return x.DiskLimit
	}
	return false
}

func (x *Capabilities) GetGvisor() bool {
	if x != nil {
		return x.Gvisor
	}
	return false
}

func (x *Capabilities) GetSystemdSlice() bool {
	if x != nil {
		return x.SystemdSlice
	}
	return false
}

func (x *Capabilities) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Capabilities) GetCgroupVersion() string {
	if x != nil {
		return x.CgroupVersion
	}
	return ""
}

type Offer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Cores            float64                `protobuf:"fixed64,1,opt,name=cores,proto3" json:"cores,omitempty"`
	MemoryMb         int32                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	DiskMb           int32                  `protobuf:"varint,3,opt,name=disk_mb,json=diskMb,proto3" json:"disk_mb,omitempty"`
	BandwidthMbMonth int64                  `protobuf:"varint,4,opt,name=bandwidth_mb_month,json=bandwidthMbMonth,proto3" json:"bandwidth_mb_month,omitempty"`
	ImageCacheMb     int32                  `protobuf:"varint,5,opt,name=image_cache_mb,json=imageCacheMb,proto3" json:"image_cache_mb,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Offer) Reset() {
	*x = Offer{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Offer) GetCores() float64 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *Offer) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *Offer) GetDiskMb() int32 {
	if x != nil {
		return x.DiskMb
	}
	return 0
}

func (x *Offer) GetBandwidthMbMonth() int64 {
	if x != nil {
		return x.BandwidthMbMonth
	}
	return 0
}

func (x *Offer) GetImageCacheMb() int32 {
	if x != nil {
		return x.ImageCacheMb
	}
	return 0
}

type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	HeartbeatS    int32                  `protobuf:"varint,2,opt,name=heartbeat_s,json=heartbeatS,proto3" json:"heartbeat_s,omitempty"`
	LeaseS        int32                  `protobuf:"varint,3,opt,name=lease_s,json=leaseS,proto3" json:"lease_s,omitempty"` // agent fences at this many seconds without ack
	BenchmarkNow  bool                   `protobuf:"varint,4,opt,name=benchmark_now,json=benchmarkNow,proto3" json:"benchmark_now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterAck) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterAck) GetHeartbeatS() int32 {
	if x != nil {
		return x.HeartbeatS
	}
	return 0
}

func (x *RegisterAck) GetLeaseS() int32 {
	if x != nil {
		return x.LeaseS
	}
	return 0
}

func (x *RegisterAck) GetBenchmarkNow() bool {
	if x != nil {
		return x.BenchmarkNow
	}
	return false
}

type Heartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Seq            int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	RunningTaskIds []string               `protobuf:"bytes,2,rep,name=running_task_ids,json=runningTaskIds,proto3" json:"running_task_ids,omitempty"` // re-announce for adoption
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Heartbeat) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Heartbeat) GetRunningTaskIds() []string {
	if x != nil {
		return x.RunningTaskIds
	}
	return nil
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatAck) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type CapacityReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offer         *Offer                 `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
	FreeCores     float64                `protobuf:"fixed64,2,opt,name=free_cores,json=freeCores,proto3" json:"free_cores,omitempty"`
	FreeMemoryMb  int32                  `protobuf:"varint,3,opt,name=free_memory_mb,json=freeMemoryMb,proto3" json:"free_memory_mb,omitempty"`
	FreeDiskMb    int32                  `protobuf:"varint,4,opt,name=free_disk_mb,json=freeDiskMb,proto3" json:"free_disk_mb,omitempty"`
	LoadAvg       float64                `protobuf:"fixed64,5,opt,name=load_avg,json=loadAvg,proto3" json:"load_avg,omitempty"`
	TempCelsius   float64                `protobuf:"fixed64,6,opt,name=temp_celsius,json=tempCelsius,proto3" json:"temp_celsius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapacityReport) Reset() {
	*x = CapacityReport{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapacityReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapacityReport) ProtoMessage() {}

func (x *CapacityReport) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapacityReport.ProtoReflect.Descriptor instead.
func (*CapacityReport) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *CapacityReport) GetOffer() *Offer {
	if x != nil {
		return x.Offer
	}
	return nil
}

func (x *CapacityReport) GetFreeCores() float64 {
	if x != nil {
		return x.FreeCores
	}
	return 0
}

func (x *CapacityReport) GetFreeMemoryMb() int32 {
	if x != nil {
		return x.FreeMemoryMb
	}
	return 0
}

func (x *CapacityReport) GetFreeDiskMb() int32 {
	if x != nil {
		return x.FreeDiskMb
	}
	return 0
}

func (x *CapacityReport) GetLoadAvg() float64 {
	if x != nil {
		return x.LoadAvg
	}
	return 0
}

func (x *CapacityReport) GetTempCelsius() float64 {
	if x != nil {
		return x.TempCelsius
	}
	return 0
}

type CachedImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CachedImage) Reset() {
	*x = CachedImage{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CachedImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedImage) ProtoMessage() {}

func (x *CachedImage) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedImage.ProtoReflect.Descriptor instead.
func (*CachedImage) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *CachedImage) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *CachedImage) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type CacheDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pulled        []*CachedImage         `protobuf:"bytes,1,rep,name=pulled,proto3" json:"pulled,omitempty"`
	Evicted       []string               `protobuf:"bytes,2,rep,name=evicted,proto3" json:"evicted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheDelta) Reset() {
	*x = CacheDelta{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheDelta) ProtoMessage() {}

func (x *CacheDelta) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheDelta.ProtoReflect.Descriptor instead.
func (*CacheDelta) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *CacheDelta) GetPulled() []*CachedImage {
	if x != nil {
		return x.Pulled
	}
	return nil
}

func (x *CacheDelta) GetEvicted() []string {
	if x != nil {
		return x.Evicted
	}
	return nil
}

type Dispatch struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Image              string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"` // digest-pinned
	Entrypoint         []string               `protobuf:"bytes,3,rep,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Args               []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	Env                map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Workdir            string                 `protobuf:"bytes,6,opt,name=workdir,proto3" json:"workdir,omitempty"`
	Limits             *Limits                `protobuf:"bytes,7,opt,name=limits,proto3" json:"limits,omitempty"`
	Isolation          string                 `protobuf:"bytes,8,opt,name=isolation,proto3" json:"isolation,omitempty"`
	Targets            []*TunnelTarget        `protobuf:"bytes,9,rep,name=targets,proto3" json:"targets,omitempty"`
	LeaseExpiresUnixMs int64                  `protobuf:"varint,10,opt,name=lease_expires_unix_ms,json=leaseExpiresUnixMs,proto3" json:"lease_expires_unix_ms,omitempty"`
	// attempt is how many times this task has been dispatched before,
	// starting at 0 for the first attempt - see store.Task.Attempt. The
	// agent uses it to make its container name unique per attempt, so a
	// retry redispatched to a different node never collides with a
	// container an earlier (possibly still-running, possibly just
	// unreachable) attempt left behind.
	Attempt       int32 `protobuf:"varint,11,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dispatch) Reset() {
	*x = Dispatch{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dispatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dispatch) ProtoMessage() {}

func (x *Dispatch) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dispatch.ProtoReflect.Descriptor instead.
func (*Dispatch) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *Dispatch) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Dispatch) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Dispatch) GetEntrypoint() []string {
	if x != nil {
		return x.Entrypoint
	}
	return nil
}

func (x *Dispatch) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Dispatch) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Dispatch) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *Dispatch) GetLimits() *Limits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *Dispatch) GetIsolation() string {
	if x != nil {
		return x.Isolation
	}
	return ""
}

func (x *Dispatch) GetTargets() []*TunnelTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Dispatch) GetLeaseExpiresUnixMs() int64 {
	if x != nil {
		return x.LeaseExpiresUnixMs
	}
	return 0
}

func (x *Dispatch) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type Limits struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuCores         float64                `protobuf:"fixed64,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMb         int32                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	DiskMb           int32                  `protobuf:"varint,3,opt,name=disk_mb,json=diskMb,proto3" json:"disk_mb,omitempty"`
	TmpfsMb          int32                  `protobuf:"varint,4,opt,name=tmpfs_mb,json=tmpfsMb,proto3" json:"tmpfs_mb,omitempty"`
	Pids             int32                  `protobuf:"varint,5,opt,name=pids,proto3" json:"pids,omitempty"`
	WallTimeoutS     int32                  `protobuf:"varint,6,opt,name=wall_timeout_s,json=wallTimeoutS,proto3" json:"wall_timeout_s,omitempty"`
	NoOutputTimeoutS int32                  `protobuf:"varint,7,opt,name=no_output_timeout_s,json=noOutputTimeoutS,proto3" json:"no_output_timeout_s,omitempty"`
	EgressMb         int32                  `protobuf:"varint,8,opt,name=egress_mb,json=egressMb,proto3" json:"egress_mb,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Limits) Reset() {
	*x = Limits{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limits) ProtoMessage() {}

func (x *Limits) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limits.ProtoReflect.Descriptor instead.
func (*Limits) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *Limits) GetCpuCores() float64 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *Limits) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *Limits) GetDiskMb() int32 {
	if x != nil {
		return x.DiskMb
	}
	return 0
}

func (x *Limits) GetTmpfsMb() int32 {
	if x != nil {
		return x.TmpfsMb
	}
	return 0
}

func (x *Limits) GetPids() int32 {
	if x != nil {
		return x.Pids
	}
	return 0
}

func (x *Limits) GetWallTimeoutS() int32 {
	if x != nil {
		return x.WallTimeoutS
	}
	return 0
}

func (x *Limits) GetNoOutputTimeoutS() int32 {
	if x != nil {
		return x.NoOutputTimeoutS
	}
	return 0
}

func (x *Limits) GetEgressMb() int32 {
	if x != nil {
		return x.EgressMb
	}
	return 0
}

type TunnelTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"` // what the container resolves
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	NoisePubkey   []byte                 `protobuf:"bytes,4,opt,name=noise_pubkey,json=noisePubkey,proto3" json:"noise_pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelTarget) Reset() {
	*x = TunnelTarget{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelTarget) ProtoMessage() {}

func (x *TunnelTarget) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelTarget.ProtoReflect.Descriptor instead.
func (*TunnelTarget) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *TunnelTarget) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *TunnelTarget) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *TunnelTarget) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *TunnelTarget) GetNoisePubkey() []byte {
	if x != nil {
		return x.NoisePubkey
	}
	return nil
}

type TaskAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAccepted) Reset() {
	*x = TaskAccepted{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAccepted) ProtoMessage() {}

func (x *TaskAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAccepted.ProtoReflect.Descriptor instead.
func (*TaskAccepted) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *TaskAccepted) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRejected) Reset() {
	*x = TaskRejected{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRejected) ProtoMessage() {}

func (x *TaskRejected) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRejected.ProtoReflect.Descriptor instead.
func (*TaskRejected) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *TaskRejected) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TaskStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AtUnixMs      int64                  `protobuf:"varint,2,opt,name=at_unix_ms,json=atUnixMs,proto3" json:"at_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStarted) Reset() {
	*x = TaskStarted{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStarted) ProtoMessage() {}

func (x *TaskStarted) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStarted.ProtoReflect.Descriptor instead.
func (*TaskStarted) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *TaskStarted) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStarted) GetAtUnixMs() int64 {
	if x != nil {
		return x.AtUnixMs
	}
	return 0
}

type TaskFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ExitReason    string                 `protobuf:"bytes,3,opt,name=exit_reason,json=exitReason,proto3" json:"exit_reason,omitempty"`
	AtUnixMs      int64                  `protobuf:"varint,4,opt,name=at_unix_ms,json=atUnixMs,proto3" json:"at_unix_ms,omitempty"`
	BytesSent     int64                  `protobuf:"varint,5,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesRecv     int64                  `protobuf:"varint,6,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
	ColdPullBytes int64                  `protobuf:"varint,7,opt,name=cold_pull_bytes,json=coldPullBytes,proto3" json:"cold_pull_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskFinished) Reset() {
	*x = TaskFinished{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskFinished) ProtoMessage() {}

func (x *TaskFinished) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskFinished.ProtoReflect.Descriptor instead.
func (*TaskFinished) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *TaskFinished) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskFinished) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskFinished) GetExitReason() string {
	if x != nil {
		return x.ExitReason
	}
	return ""
}

func (x *TaskFinished) GetAtUnixMs() int64 {
	if x != nil {
		return x.AtUnixMs
	}
	return 0
}

func (x *TaskFinished) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *TaskFinished) GetBytesRecv() int64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

func (x *TaskFinished) GetColdPullBytes() int64 {
	if x != nil {
		return x.ColdPullBytes
	}
	return 0
}

type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *Cancel) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Cancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Lines         []*LogLine             `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *LogBatch) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *LogBatch) GetLines() []*LogLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	AtUnixMs      int64                  `protobuf:"varint,3,opt,name=at_unix_ms,json=atUnixMs,proto3" json:"at_unix_ms,omitempty"`
	Line          string                 `protobuf:"bytes,4,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_lazycake_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *LogLine) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LogLine) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogLine) GetAtUnixMs() int64 {
	if x != nil {
		return x.AtUnixMs
	}
	return 0
}

func (x *LogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

var File_lazycake_v1_agent_proto protoreflect.FileDescriptor

const file_lazycake_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x17lazycake/v1/agent.proto\x12\vlazycake.v1\"\xc7\x04\n" +
	"\fAgentMessage\x123\n" +
	"\bregister\x18\x01 \x01(\v2\x15.lazycake.v1.RegisterH\x00R\bregister\x126\n" +
	"\theartbeat\x18\x02 \x01(\v2\x16.lazycake.v1.HeartbeatH\x00R\theartbeat\x129\n" +
	"\bcapacity\x18\x03 \x01(\v2\x1b.lazycake.v1.CapacityReportH\x00R\bcapacity\x12:\n" +
	"\vcache_delta\x18\x04 \x01(\v2\x17.lazycake.v1.CacheDeltaH\x00R\n" +
	"cacheDelta\x127\n" +
	"\baccepted\x18\x05 \x01(\v2\x19.lazycake.v1.TaskAcceptedH\x00R\baccepted\x127\n" +
	"\brejected\x18\x06 \x01(\v2\x19.lazycake.v1.TaskRejectedH\x00R\brejected\x124\n" +
	"\astarted\x18\a \x01(\v2\x18.lazycake.v1.TaskStartedH\x00R\astarted\x127\n" +
	"\bfinished\x18\b \x01(\v2\x19.lazycake.v1.TaskFinishedH\x00R\bfinished\x12+\n" +
	"\x04logs\x18\t \x01(\v2\x15.lazycake.v1.LogBatchH\x00R\x04logs\x12=\n" +
	"\fbench_report\x18\n" +
	" \x01(\v2\x18.lazycake.v1.BenchReportH\x00R\vbenchReportB\x06\n" +
	"\x04body\"#\n" +
	"\vBenchReport\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\"\x81\x02\n" +
	"\x12CoordinatorMessage\x12=\n" +
	"\fregister_ack\x18\x01 \x01(\v2\x18.lazycake.v1.RegisterAckH\x00R\vregisterAck\x12@\n" +
	"\rheartbeat_ack\x18\x02 \x01(\v2\x19.lazycake.v1.HeartbeatAckH\x00R\fheartbeatAck\x123\n" +
	"\bdispatch\x18\x03 \x01(\v2\x15.lazycake.v1.DispatchH\x00R\bdispatch\x12-\n" +
	"\x06cancel\x18\x04 \x01(\v2\x13.lazycake.v1.CancelH\x00R\x06cancelB\x06\n" +
	"\x04body\"\xdc\x02\n" +
	"\bRegister\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x1b\n" +
	"\tcpu_flags\x18\x04 \x03(\tR\bcpuFlags\x12-\n" +
	"\x04caps\x18\x05 \x01(\v2\x19.lazycake.v1.CapabilitiesR\x04caps\x12(\n" +
	"\x05offer\x18\x06 \x01(\v2\x12.lazycake.v1.OfferR\x05offer\x12\x17\n" +
	"\aboot_id\x18\a \x01(\tR\x06bootId\x12\x1f\n" +
	"\vinstance_id\x18\b \x01(\tR\n" +
	"instanceId\x120\n" +
	"\x06images\x18\t \x03(\v2\x18.lazycake.v1.CachedImageR\x06images\x12(\n" +
	"\x10running_task_ids\x18\n" +
	" \x03(\tR\x0erunningTaskIds\"\x8a\x02\n" +
	"\fCapabilities\x12!\n" +
	"\fmemory_limit\x18\x01 \x01(\bR\vmemoryLimit\x12\x1b\n" +
	"\tcpu_quota\x18\x02 \x01(\bR\bcpuQuota\x12\x1d\n" +
	"\n" +
	"pids_limit\x18\x03 \x01(\bR\tpidsLimit\x12\x1d\n" +
	"\n" +
	"disk_limit\x18\x04 \x01(\bR\tdiskLimit\x12\x16\n" +
	"\x06gvisor\x18\x05 \x01(\bR\x06gvisor\x12#\n" +
	"\rsystemd_slice\x18\x06 \x01(\bR\fsystemdSlice\x12\x18\n" +
	"\aruntime\x18\a \x01(\tR\aruntime\x12%\n" +
	"\x0ecgroup_version\x18\b \x01(\tR\rcgroupVersion\"\xa7\x01\n" +
	"\x05Offer\x12\x14\n" +
	"\x05cores\x18\x01 \x01(\x01R\x05cores\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x05R\bmemoryMb\x12\x17\n" +
	"\adisk_mb\x18\x03 \x01(\x05R\x06diskMb\x12,\n" +
	"\x12bandwidth_mb_month\x18\x04 \x01(\x03R\x10bandwidthMbMonth\x12$\n" +
	"\x0eimage_cache_mb\x18\x05 \x01(\x05R\fimageCacheMb\"\x85\x01\n" +
	"\vRegisterAck\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vheartbeat_s\x18\x02 \x01(\x05R\n" +
	"heartbeatS\x12\x17\n" +
	"\alease_s\x18\x03 \x01(\x05R\x06leaseS\x12#\n" +
	"\rbenchmark_now\x18\x04 \x01(\bR\fbenchmarkNow\"G\n" +
	"\tHeartbeat\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12(\n" +
	"\x10running_task_ids\x18\x02 \x03(\tR\x0erunningTaskIds\" \n" +
	"\fHeartbeatAck\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\"\xdf\x01\n" +
	"\x0eCapacityReport\x12(\n" +
	"\x05offer\x18\x01 \x01(\v2\x12.lazycake.v1.OfferR\x05offer\x12\x1d\n" +
	"\n" +
	"free_cores\x18\x02 \x01(\x01R\tfreeCores\x12$\n" +
	"\x0efree_memory_mb\x18\x03 \x01(\x05R\ffreeMemoryMb\x12 \n" +
	"\ffree_disk_mb\x18\x04 \x01(\x05R\n" +
	"freeDiskMb\x12\x19\n" +
	"\bload_avg\x18\x05 \x01(\x01R\aloadAvg\x12!\n" +
	"\ftemp_celsius\x18\x06 \x01(\x01R\vtempCelsius\"D\n" +
	"\vCachedImage\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\"X\n" +
	"\n" +
	"CacheDelta\x120\n" +
	"\x06pulled\x18\x01 \x03(\v2\x18.lazycake.v1.CachedImageR\x06pulled\x12\x18\n" +
	"\aevicted\x18\x02 \x03(\tR\aevicted\"\xbe\x03\n" +
	"\bDispatch\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x03 \x03(\tR\n" +
	"entrypoint\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x120\n" +
	"\x03env\x18\x05 \x03(\v2\x1e.lazycake.v1.Dispatch.EnvEntryR\x03env\x12\x18\n" +
	"\aworkdir\x18\x06 \x01(\tR\aworkdir\x12+\n" +
	"\x06limits\x18\a \x01(\v2\x13.lazycake.v1.LimitsR\x06limits\x12\x1c\n" +
	"\tisolation\x18\b \x01(\tR\tisolation\x123\n" +
	"\atargets\x18\t \x03(\v2\x19.lazycake.v1.TunnelTargetR\atargets\x121\n" +
	"\x15lease_expires_unix_ms\x18\n" +
	" \x01(\x03R\x12leaseExpiresUnixMs\x12\x18\n" +
	"\aattempt\x18\v \x01(\x05R\aattempt\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfc\x01\n" +
	"\x06Limits\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x01R\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x05R\bmemoryMb\x12\x17\n" +
	"\adisk_mb\x18\x03 \x01(\x05R\x06diskMb\x12\x19\n" +
	"\btmpfs_mb\x18\x04 \x01(\x05R\atmpfsMb\x12\x12\n" +
	"\x04pids\x18\x05 \x01(\x05R\x04pids\x12$\n" +
	"\x0ewall_timeout_s\x18\x06 \x01(\x05R\fwallTimeoutS\x12-\n" +
	"\x13no_output_timeout_s\x18\a \x01(\x05R\x10noOutputTimeoutS\x12\x1b\n" +
	"\tegress_mb\x18\b \x01(\x05R\begressMb\"\x80\x01\n" +
	"\fTunnelTarget\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12!\n" +
	"\fnoise_pubkey\x18\x04 \x01(\fR\vnoisePubkey\"'\n" +
	"\fTaskAccepted\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"?\n" +
	"\fTaskRejected\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"D\n" +
	"\vTaskStarted\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1c\n" +
	"\n" +
	"at_unix_ms\x18\x02 \x01(\x03R\batUnixMs\"\xe9\x01\n" +
	"\fTaskFinished\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x1f\n" +
	"\vexit_reason\x18\x03 \x01(\tR\n" +
	"exitReason\x12\x1c\n" +
	"\n" +
	"at_unix_ms\x18\x04 \x01(\x03R\batUnixMs\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x05 \x01(\x03R\tbytesSent\x12\x1d\n" +
	"\n" +
	"bytes_recv\x18\x06 \x01(\x03R\tbytesRecv\x12&\n" +
	"\x0fcold_pull_bytes\x18\a \x01(\x03R\rcoldPullBytes\"9\n" +
	"\x06Cancel\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"O\n" +
	"\bLogBatch\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12*\n" +
	"\x05lines\x18\x02 \x03(\v2\x14.lazycake.v1.LogLineR\x05lines\"e\n" +
	"\aLogLine\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x1c\n" +
	"\n" +
	"at_unix_ms\x18\x03 \x01(\x03R\batUnixMs\x12\x12\n" +
	"\x04line\x18\x04 \x01(\tR\x04line2Y\n" +
	"\fAgentService\x12I\n" +
	"\aConnect\x12\x19.lazycake.v1.AgentMessage\x1a\x1f.lazycake.v1.CoordinatorMessage(\x010\x01B:Z8github.com/mkassab215/lazycake/internal/proto/lazycakev1b\x06proto3"

var (
	file_lazycake_v1_agent_proto_rawDescOnce sync.Once
	file_lazycake_v1_agent_proto_rawDescData []byte
)

func file_lazycake_v1_agent_proto_rawDescGZIP() []byte {
	file_lazycake_v1_agent_proto_rawDescOnce.Do(func() {
		file_lazycake_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lazycake_v1_agent_proto_rawDesc), len(file_lazycake_v1_agent_proto_rawDesc)))
	})
	return file_lazycake_v1_agent_proto_rawDescData
}

var file_lazycake_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_lazycake_v1_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),       // 0: lazycake.v1.AgentMessage
	(*BenchReport)(nil),        // 1: lazycake.v1.BenchReport
	(*CoordinatorMessage)(nil), // 2: lazycake.v1.CoordinatorMessage
	(*Register)(nil),           // 3: lazycake.v1.Register
	(*Capabilities)(nil),       // 4: lazycake.v1.Capabilities
	(*Offer)(nil),              // 5: lazycake.v1.Offer
	(*RegisterAck)(nil),        // 6: lazycake.v1.RegisterAck
	(*Heartbeat)(nil),          // 7: lazycake.v1.Heartbeat
	(*HeartbeatAck)(nil),       // 8: lazycake.v1.HeartbeatAck
	(*CapacityReport)(nil),     // 9: lazycake.v1.CapacityReport
	(*CachedImage)(nil),        // 10: lazycake.v1.CachedImage
	(*CacheDelta)(nil),         // 11: lazycake.v1.CacheDelta
	(*Dispatch)(nil),           // 12: lazycake.v1.Dispatch
	(*Limits)(nil),             // 13: lazycake.v1.Limits
	(*TunnelTarget)(nil),       // 14: lazycake.v1.TunnelTarget
	(*TaskAccepted)(nil),       // 15: lazycake.v1.TaskAccepted
	(*TaskRejected)(nil),       // 16: lazycake.v1.TaskRejected
	(*TaskStarted)(nil),        // 17: lazycake.v1.TaskStarted
	(*TaskFinished)(nil),       // 18: lazycake.v1.TaskFinished
	(*Cancel)(nil),             // 19: lazycake.v1.Cancel
	(*LogBatch)(nil),           // 20: lazycake.v1.LogBatch
	(*LogLine)(nil),            // 21: lazycake.v1.LogLine
	nil,                        // 22: lazycake.v1.Dispatch.EnvEntry
}
var file_lazycake_v1_agent_proto_depIdxs = []int32{
	3,  // 0: lazycake.v1.AgentMessage.register:type_name -> lazycake.v1.Register
	7,  // 1: lazycake.v1.AgentMessage.heartbeat:type_name -> lazycake.v1.Heartbeat
	9,  // 2: lazycake.v1.AgentMessage.capacity:type_name -> lazycake.v1.CapacityReport
	11, // 3: lazycake.v1.AgentMessage.cache_delta:type_name -> lazycake.v1.CacheDelta
	15, // 4: lazycake.v1.AgentMessage.accepted:type_name -> lazycake.v1.TaskAccepted
	16, // 5: lazycake.v1.AgentMessage.rejected:type_name -> lazycake.v1.TaskRejected
	17, // 6: lazycake.v1.AgentMessage.started:type_name -> lazycake.v1.TaskStarted
	18, // 7: lazycake.v1.AgentMessage.finished:type_name -> lazycake.v1.TaskFinished
	20, // 8: lazycake.v1.AgentMessage.logs:type_name -> lazycake.v1.LogBatch
	1,  // 9: lazycake.v1.AgentMessage.bench_report:type_name -> lazycake.v1.BenchReport
	6,  // 10: lazycake.v1.CoordinatorMessage.register_ack:type_name -> lazycake.v1.RegisterAck
	8,  // 11: lazycake.v1.CoordinatorMessage.heartbeat_ack:type_name -> lazycake.v1.HeartbeatAck
	12, // 12: lazycake.v1.CoordinatorMessage.dispatch:type_name -> lazycake.v1.Dispatch
	19, // 13: lazycake.v1.CoordinatorMessage.cancel:type_name -> lazycake.v1.Cancel
	4,  // 14: lazycake.v1.Register.caps:type_name -> lazycake.v1.Capabilities
	5,  // 15: lazycake.v1.Register.offer:type_name -> lazycake.v1.Offer
	10, // 16: lazycake.v1.Register.images:type_name -> lazycake.v1.CachedImage
	5,  // 17: lazycake.v1.CapacityReport.offer:type_name -> lazycake.v1.Offer
	10, // 18: lazycake.v1.CacheDelta.pulled:type_name -> lazycake.v1.CachedImage
	22, // 19: lazycake.v1.Dispatch.env:type_name -> lazycake.v1.Dispatch.EnvEntry
	13, // 20: lazycake.v1.Dispatch.limits:type_name -> lazycake.v1.Limits
	14, // 21: lazycake.v1.Dispatch.targets:type_name -> lazycake.v1.TunnelTarget
	21, // 22: lazycake.v1.LogBatch.lines:type_name -> lazycake.v1.LogLine
	0,  // 23: lazycake.v1.AgentService.Connect:input_type -> lazycake.v1.AgentMessage
	2,  // 24: lazycake.v1.AgentService.Connect:output_type -> lazycake.v1.CoordinatorMessage
	24, // [24:25] is the sub-list for method output_type
	23, // [23:24] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_lazycake_v1_agent_proto_init() }
func file_lazycake_v1_agent_proto_init() {
	if File_lazycake_v1_agent_proto != nil {
		return
	}
	file_lazycake_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Capacity)(nil),
		(*AgentMessage_CacheDelta)(nil),
		(*AgentMessage_Accepted)(nil),
		(*AgentMessage_Rejected)(nil),
		(*AgentMessage_Started)(nil),
		(*AgentMessage_Finished)(nil),
		(*AgentMessage_Logs)(nil),
		(*AgentMessage_BenchReport)(nil),
	}
	file_lazycake_v1_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*CoordinatorMessage_RegisterAck)(nil),
		(*CoordinatorMessage_HeartbeatAck)(nil),
		(*CoordinatorMessage_Dispatch)(nil),
		(*CoordinatorMessage_Cancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lazycake_v1_agent_proto_rawDesc), len(file_lazycake_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lazycake_v1_agent_proto_goTypes,
		DependencyIndexes: file_lazycake_v1_agent_proto_depIdxs,
		MessageInfos:      file_lazycake_v1_agent_proto_msgTypes,
	}.Build()
	File_lazycake_v1_agent_proto = out.File
	file_lazycake_v1_agent_proto_goTypes = nil
	file_lazycake_v1_agent_proto_depIdxs = nil
}
