// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: lazycake/v1/customer.proto

package lazycakev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskLimits struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuCores         float64                `protobuf:"fixed64,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMb         int32                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	DiskMb           int32                  `protobuf:"varint,3,opt,name=disk_mb,json=diskMb,proto3" json:"disk_mb,omitempty"`
	TmpfsMb          int32                  `protobuf:"varint,4,opt,name=tmpfs_mb,json=tmpfsMb,proto3" json:"tmpfs_mb,omitempty"`
	Pids             int32                  `protobuf:"varint,5,opt,name=pids,proto3" json:"pids,omitempty"`
	WallTimeoutS     int32                  `protobuf:"varint,6,opt,name=wall_timeout_s,json=wallTimeoutS,proto3" json:"wall_timeout_s,omitempty"`
	NoOutputTimeoutS int32                  `protobuf:"varint,7,opt,name=no_output_timeout_s,json=noOutputTimeoutS,proto3" json:"no_output_timeout_s,omitempty"`
	EgressMb         int32                  `protobuf:"varint,8,opt,name=egress_mb,json=egressMb,proto3" json:"egress_mb,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskLimits) Reset() {
	*x = TaskLimits{}
	mi := &file_lazycake_v1_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLimits) ProtoMessage() {}

func (x *TaskLimits) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLimits.ProtoReflect.Descriptor instead.
func (*TaskLimits) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_customer_proto_rawDescGZIP(), []int{0}
}

func (x *TaskLimits) GetCpuCores() float64 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *TaskLimits) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *TaskLimits) GetDiskMb() int32 {
	if x != nil {
		return x.DiskMb
	}
	return 0
}

func (x *TaskLimits) GetTmpfsMb() int32 {
	if x != nil {
		return x.TmpfsMb
	}
	return 0
}

func (x *TaskLimits) GetPids() int32 {
	if x != nil {
		return x.Pids
	}
	return 0
}

func (x *TaskLimits) GetWallTimeoutS() int32 {
	if x != nil {
		return x.WallTimeoutS
	}
	return 0
}

func (x *TaskLimits) GetNoOutputTimeoutS() int32 {
	if x != nil {
		return x.NoOutputTimeoutS
	}
	return 0
}

func (x *TaskLimits) GetEgressMb() int32 {
	if x != nil {
		return x.EgressMb
	}
	return 0
}

// TunnelTargetSpec is one hostname the task's container will be allowed to
// resolve and connect to, reached through gateway_id. hostname is exactly
// what customer code connects to (e.g. "db.acme.com"); the coordinator
// resolves gateway_id to that gateway's published Noise key before
// dispatch, and internal/agent/netns's stub resolver only ever answers
// for hostnames listed here.
type TunnelTargetSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelTargetSpec) Reset() {
	*x = TunnelTargetSpec{}
	mi := &file_lazycake_v1_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelTargetSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelTargetSpec) ProtoMessage() {}

func (x *TunnelTargetSpec) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelTargetSpec.ProtoReflect.Descriptor instead.
func (*TunnelTargetSpec) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_customer_proto_rawDescGZIP(), []int{1}
}

func (x *TunnelTargetSpec) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *TunnelTargetSpec) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *TunnelTargetSpec) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type SubmitTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Image          string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"` // must be digest-pinned: "repo@sha256:..."
	Entrypoint     []string               `protobuf:"bytes,2,rep,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Args           []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Workdir        string                 `protobuf:"bytes,5,opt,name=workdir,proto3" json:"workdir,omitempty"`
	Limits         *TaskLimits            `protobuf:"bytes,6,opt,name=limits,proto3" json:"limits,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Targets        []*TunnelTargetSpec    `protobuf:"bytes,8,rep,name=targets,proto3" json:"targets,omitempty"`   // at most 3 - PLAN.md overview
	Delivery       string                 `protobuf:"bytes,9,opt,name=delivery,proto3" json:"delivery,omitempty"` // "at_most_once" (default) | "at_least_once"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitTaskRequest) Reset() {
	*x = SubmitTaskRequest{}
	mi := &file_lazycake_v1_customer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskRequest) ProtoMessage() {}

func (x *SubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_customer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_customer_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitTaskRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SubmitTaskRequest) GetEntrypoint() []string {
	if x != nil {
		return x.Entrypoint
	}
	return nil
}

func (x *SubmitTaskRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *SubmitTaskRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *SubmitTaskRequest) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *SubmitTaskRequest) GetLimits() *TaskLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *SubmitTaskRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SubmitTaskRequest) GetTargets() []*TunnelTargetSpec {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *SubmitTaskRequest) GetDelivery() string {
	if x != nil {
		return x.Delivery
	}
	return ""
}

type SubmitTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResponse) Reset() {
	*x = SubmitTaskResponse{}
	mi := &file_lazycake_v1_customer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResponse) ProtoMessage() {}

func (x *SubmitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_customer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskResponse) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_customer_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_lazycake_v1_customer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_customer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_customer_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	State            string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	ExitCode         int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	HasExitCode      bool                   `protobuf:"varint,4,opt,name=has_exit_code,json=hasExitCode,proto3" json:"has_exit_code,omitempty"`
	ExitReason       string                 `protobuf:"bytes,5,opt,name=exit_reason,json=exitReason,proto3" json:"exit_reason,omitempty"`
	NodeId           string                 `protobuf:"bytes,6,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CreatedAtUnixMs  int64                  `protobuf:"varint,7,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	StartedAtUnixMs  int64                  `protobuf:"varint,8,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	FinishedAtUnixMs int64                  `protobuf:"varint,9,opt,name=finished_at_unix_ms,json=finishedAtUnixMs,proto3" json:"finished_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskStatus) Reset() {
	*x = TaskStatus{}
	mi := &file_lazycake_v1_customer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatus) ProtoMessage() {}

func (x *TaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_customer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatus.ProtoReflect.Descriptor instead.
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_customer_proto_rawDescGZIP(), []int{5}
}

func (x *TaskStatus) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TaskStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskStatus) GetHasExitCode() bool {
	if x != nil {
		return x.HasExitCode
	}
	return false
}

func (x *TaskStatus) GetExitReason() string {
	if x != nil {
		return x.ExitReason
	}
	return ""
}

func (x *TaskStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TaskStatus) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *TaskStatus) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

func (x *TaskStatus) GetFinishedAtUnixMs() int64 {
	if x != nil {
		return x.FinishedAtUnixMs
	}
	return 0
}

type StreamLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_lazycake_v1_customer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_customer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_customer_proto_rawDescGZIP(), []int{6}
}

func (x *StreamLogsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StreamLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type TaskLogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	AtUnixMs      int64                  `protobuf:"varint,3,opt,name=at_unix_ms,json=atUnixMs,proto3" json:"at_unix_ms,omitempty"`
	Line          string                 `protobuf:"bytes,4,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogLine) Reset() {
	*x = TaskLogLine{}
	mi := &file_lazycake_v1_customer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogLine) ProtoMessage() {}

func (x *TaskLogLine) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_customer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogLine.ProtoReflect.Descriptor instead.
func (*TaskLogLine) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_customer_proto_rawDescGZIP(), []int{7}
}

func (x *TaskLogLine) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TaskLogLine) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *TaskLogLine) GetAtUnixMs() int64 {
	if x != nil {
		return x.AtUnixMs
	}
	return 0
}

func (x *TaskLogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_lazycake_v1_customer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_customer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_customer_proto_rawDescGZIP(), []int{8}
}

type NodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Connected     bool                   `protobuf:"varint,3,opt,name=connected,proto3" json:"connected,omitempty"`
	OfferCores    float64                `protobuf:"fixed64,4,opt,name=offer_cores,json=offerCores,proto3" json:"offer_cores,omitempty"`
	OfferMemoryMb int32                  `protobuf:"varint,5,opt,name=offer_memory_mb,json=offerMemoryMb,proto3" json:"offer_memory_mb,omitempty"`
	OfferDiskMb   int32                  `protobuf:"varint,6,opt,name=offer_disk_mb,json=offerDiskMb,proto3" json:"offer_disk_mb,omitempty"`
	TrustScore    float64                `protobuf:"fixed64,7,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_lazycake_v1_customer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_customer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_customer_proto_rawDescGZIP(), []int{9}
}

func (x *NodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatus) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *NodeStatus) GetOfferCores() float64 {
	if x != nil {
		return x.OfferCores
	}
	return 0
}

func (x *NodeStatus) GetOfferMemoryMb() int32 {
	if x != nil {
		return x.OfferMemoryMb
	}
	return 0
}

func (x *NodeStatus) GetOfferDiskMb() int32 {
	if x != nil {
		return x.OfferDiskMb
	}
	return 0
}

func (x *NodeStatus) GetTrustScore() float64 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeStatus          `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_lazycake_v1_customer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_customer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_customer_proto_rawDescGZIP(), []int{10}
}

func (x *ListNodesResponse) GetNodes() []*NodeStatus {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type CreateGatewayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Label string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// service_name:port, repeatable, e.g. "db:5432".
	Services      []string `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGatewayRequest) Reset() {
	*x = CreateGatewayRequest{}
	mi := &file_lazycake_v1_customer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGatewayRequest) ProtoMessage() {}

func (x *CreateGatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_customer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGatewayRequest.ProtoReflect.Descriptor instead.
func (*CreateGatewayRequest) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_customer_proto_rawDescGZIP(), []int{11}
}

func (x *CreateGatewayRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateGatewayRequest) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

type CreateGatewayResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	GatewayId string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	// install_token authenticates the gateway process itself
	// (LAZYCAKE_TOKEN) - shown once, not retrievable again.
	InstallToken  string `protobuf:"bytes,2,opt,name=install_token,json=installToken,proto3" json:"install_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGatewayResponse) Reset() {
	*x = CreateGatewayResponse{}
	mi := &file_lazycake_v1_customer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGatewayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGatewayResponse) ProtoMessage() {}

func (x *CreateGatewayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_customer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGatewayResponse.ProtoReflect.Descriptor instead.
func (*CreateGatewayResponse) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_customer_proto_rawDescGZIP(), []int{12}
}

func (x *CreateGatewayResponse) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *CreateGatewayResponse) GetInstallToken() string {
	if x != nil {
		return x.InstallToken
	}
	return ""
}

type ListGatewaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGatewaysRequest) Reset() {
	*x = ListGatewaysRequest{}
	mi := &file_lazycake_v1_customer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGatewaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGatewaysRequest) ProtoMessage() {}

func (x *ListGatewaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_customer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGatewaysRequest.ProtoReflect.Descriptor instead.
func (*ListGatewaysRequest) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_customer_proto_rawDescGZIP(), []int{13}
}

type GatewayStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Connected     bool                   `protobuf:"varint,3,opt,name=connected,proto3" json:"connected,omitempty"`
	Services      []string               `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayStatus) Reset() {
	*x = GatewayStatus{}
	mi := &file_lazycake_v1_customer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayStatus) ProtoMessage() {}

func (x *GatewayStatus) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_customer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayStatus.ProtoReflect.Descriptor instead.
func (*GatewayStatus) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_customer_proto_rawDescGZIP(), []int{14}
}

func (x *GatewayStatus) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *GatewayStatus) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *GatewayStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *GatewayStatus) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

type ListGatewaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateways      []*GatewayStatus       `protobuf:"bytes,1,rep,name=gateways,proto3" json:"gateways,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGatewaysResponse) Reset() {
	*x = ListGatewaysResponse{}
	mi := &file_lazycake_v1_customer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGatewaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGatewaysResponse) ProtoMessage() {}

func (x *ListGatewaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_customer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGatewaysResponse.ProtoReflect.Descriptor instead.
func (*ListGatewaysResponse) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_customer_proto_rawDescGZIP(), []int{15}
}

func (x *ListGatewaysResponse) GetGateways() []*GatewayStatus {
	if x != nil {
		return x.Gateways
	}
	return nil
}

var File_lazycake_v1_customer_proto protoreflect.FileDescriptor

const file_lazycake_v1_customer_proto_rawDesc = "" +
	"\n" +
	"\x1alazycake/v1/customer.proto\x12\vlazycake.v1\"\x80\x02\n" +
	"\n" +
	"TaskLimits\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x01R\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x05R\bmemoryMb\x12\x17\n" +
	"\adisk_mb\x18\x03 \x01(\x05R\x06diskMb\x12\x19\n" +
	"\btmpfs_mb\x18\x04 \x01(\x05R\atmpfsMb\x12\x12\n" +
	"\x04pids\x18\x05 \x01(\x05R\x04pids\x12$\n" +
	"\x0ewall_timeout_s\x18\x06 \x01(\x05R\fwallTimeoutS\x12-\n" +
	"\x13no_output_timeout_s\x18\a \x01(\x05R\x10noOutputTimeoutS\x12\x1b\n" +
	"\tegress_mb\x18\b \x01(\x05R\begressMb\"a\n" +
	"\x10TunnelTargetSpec\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"\x99\x03\n" +
	"\x11SubmitTaskRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x02 \x03(\tR\n" +
	"entrypoint\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x129\n" +
	"\x03env\x18\x04 \x03(\v2'.lazycake.v1.SubmitTaskRequest.EnvEntryR\x03env\x12\x18\n" +
	"\aworkdir\x18\x05 \x01(\tR\aworkdir\x12/\n" +
	"\x06limits\x18\x06 \x01(\v2\x17.lazycake.v1.TaskLimitsR\x06limits\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x127\n" +
	"\atargets\x18\b \x03(\v2\x1d.lazycake.v1.TunnelTargetSpecR\atargets\x12\x1a\n" +
	"\bdelivery\x18\t \x01(\tR\bdelivery\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x12SubmitTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xbf\x02\n" +
	"\n" +
	"TaskStatus\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\"\n" +
	"\rhas_exit_code\x18\x04 \x01(\bR\vhasExitCode\x12\x1f\n" +
	"\vexit_reason\x18\x05 \x01(\tR\n" +
	"exitReason\x12\x17\n" +
	"\anode_id\x18\x06 \x01(\tR\x06nodeId\x12+\n" +
	"\x12created_at_unix_ms\x18\a \x01(\x03R\x0fcreatedAtUnixMs\x12+\n" +
	"\x12started_at_unix_ms\x18\b \x01(\x03R\x0fstartedAtUnixMs\x12-\n" +
	"\x13finished_at_unix_ms\x18\t \x01(\x03R\x10finishedAtUnixMs\"D\n" +
	"\x11StreamLogsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\"i\n" +
	"\vTaskLogLine\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x1c\n" +
	"\n" +
	"at_unix_ms\x18\x03 \x01(\x03R\batUnixMs\x12\x12\n" +
	"\x04line\x18\x04 \x01(\tR\x04line\"\x12\n" +
	"\x10ListNodesRequest\"\xed\x01\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1c\n" +
	"\tconnected\x18\x03 \x01(\bR\tconnected\x12\x1f\n" +
	"\voffer_cores\x18\x04 \x01(\x01R\n" +
	"offerCores\x12&\n" +
	"\x0foffer_memory_mb\x18\x05 \x01(\x05R\rofferMemoryMb\x12\"\n" +
	"\roffer_disk_mb\x18\x06 \x01(\x05R\vofferDiskMb\x12\x1f\n" +
	"\vtrust_score\x18\a \x01(\x01R\n" +
	"trustScore\"B\n" +
	"\x11ListNodesResponse\x12-\n" +
	"\x05nodes\x18\x01 \x03(\v2\x17.lazycake.v1.NodeStatusR\x05nodes\"H\n" +
	"\x14CreateGatewayRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1a\n" +
	"\bservices\x18\x02 \x03(\tR\bservices\"[\n" +
	"\x15CreateGatewayResponse\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12#\n" +
	"\rinstall_token\x18\x02 \x01(\tR\finstallToken\"\x15\n" +
	"\x13ListGatewaysRequest\"~\n" +
	"\rGatewayStatus\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1c\n" +
	"\tconnected\x18\x03 \x01(\bR\tconnected\x12\x1a\n" +
	"\bservices\x18\x04 \x03(\tR\bservices\"N\n" +
	"\x14ListGatewaysResponse\x126\n" +
	"\bgateways\x18\x01 \x03(\v2\x1a.lazycake.v1.GatewayStatusR\bgateways2\xe4\x03\n" +
	"\x0fCustomerService\x12M\n" +
	"\n" +
	"SubmitTask\x12\x1e.lazycake.v1.SubmitTaskRequest\x1a\x1f.lazycake.v1.SubmitTaskResponse\x12?\n" +
	"\aGetTask\x12\x1b.lazycake.v1.GetTaskRequest\x1a\x17.lazycake.v1.TaskStatus\x12H\n" +
	"\n" +
	"StreamLogs\x12\x1e.lazycake.v1.StreamLogsRequest\x1a\x18.lazycake.v1.TaskLogLine0\x01\x12J\n" +
	"\tListNodes\x12\x1d.lazycake.v1.ListNodesRequest\x1a\x1e.lazycake.v1.ListNodesResponse\x12V\n" +
	"\rCreateGateway\x12!.lazycake.v1.CreateGatewayRequest\x1a\".lazycake.v1.CreateGatewayResponse\x12S\n" +
	"\fListGateways\x12 .lazycake.v1.ListGatewaysRequest\x1a!.lazycake.v1.ListGatewaysResponseB:Z8github.com/mkassab215/lazycake/internal/proto/lazycakev1b\x06proto3"

var (
	file_lazycake_v1_customer_proto_rawDescOnce sync.Once
	file_lazycake_v1_customer_proto_rawDescData []byte
)

func file_lazycake_v1_customer_proto_rawDescGZIP() []byte {
	file_lazycake_v1_customer_proto_rawDescOnce.Do(func() {
		file_lazycake_v1_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lazycake_v1_customer_proto_rawDesc), len(file_lazycake_v1_customer_proto_rawDesc)))
	})
	return file_lazycake_v1_customer_proto_rawDescData
}

var file_lazycake_v1_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_lazycake_v1_customer_proto_goTypes = []any{
	(*TaskLimits)(nil),            // 0: lazycake.v1.TaskLimits
	(*TunnelTargetSpec)(nil),      // 1: lazycake.v1.TunnelTargetSpec
	(*SubmitTaskRequest)(nil),     // 2: lazycake.v1.SubmitTaskRequest
	(*SubmitTaskResponse)(nil),    // 3: lazycake.v1.SubmitTaskResponse
	(*GetTaskRequest)(nil),        // 4: lazycake.v1.GetTaskRequest
	(*TaskStatus)(nil),            // 5: lazycake.v1.TaskStatus
	(*StreamLogsRequest)(nil),     // 6: lazycake.v1.StreamLogsRequest
	(*TaskLogLine)(nil),           // 7: lazycake.v1.TaskLogLine
	(*ListNodesRequest)(nil),      // 8: lazycake.v1.ListNodesRequest
	(*NodeStatus)(nil),            // 9: lazycake.v1.NodeStatus
	(*ListNodesResponse)(nil),     // 10: lazycake.v1.ListNodesResponse
	(*CreateGatewayRequest)(nil),  // 11: lazycake.v1.CreateGatewayRequest
	(*CreateGatewayResponse)(nil), // 12: lazycake.v1.CreateGatewayResponse
	(*ListGatewaysRequest)(nil),   // 13: lazycake.v1.ListGatewaysRequest
	(*GatewayStatus)(nil),         // 14: lazycake.v1.GatewayStatus
	(*ListGatewaysResponse)(nil),  // 15: lazycake.v1.ListGatewaysResponse
	nil,                           // 16: lazycake.v1.SubmitTaskRequest.EnvEntry
}
var file_lazycake_v1_customer_proto_depIdxs = []int32{
	16, // 0: lazycake.v1.SubmitTaskRequest.env:type_name -> lazycake.v1.SubmitTaskRequest.EnvEntry
	0,  // 1: lazycake.v1.SubmitTaskRequest.limits:type_name -> lazycake.v1.TaskLimits
	1,  // 2: lazycake.v1.SubmitTaskRequest.targets:type_name -> lazycake.v1.TunnelTargetSpec
	9,  // 3: lazycake.v1.ListNodesResponse.nodes:type_name -> lazycake.v1.NodeStatus
	14, // 4: lazycake.v1.ListGatewaysResponse.gateways:type_name -> lazycake.v1.GatewayStatus
	2,  // 5: lazycake.v1.CustomerService.SubmitTask:input_type -> lazycake.v1.SubmitTaskRequest
	4,  // 6: lazycake.v1.CustomerService.GetTask:input_type -> lazycake.v1.GetTaskRequest
	6,  // 7: lazycake.v1.CustomerService.StreamLogs:input_type -> lazycake.v1.StreamLogsRequest
	8,  // 8: lazycake.v1.CustomerService.ListNodes:input_type -> lazycake.v1.ListNodesRequest
	11, // 9: lazycake.v1.CustomerService.CreateGateway:input_type -> lazycake.v1.CreateGatewayRequest
	13, // 10: lazycake.v1.CustomerService.ListGateways:input_type -> lazycake.v1.ListGatewaysRequest
	3,  // 11: lazycake.v1.CustomerService.SubmitTask:output_type -> lazycake.v1.SubmitTaskResponse
	5,  // 12: lazycake.v1.CustomerService.GetTask:output_type -> lazycake.v1.TaskStatus
	7,  // 13: lazycake.v1.CustomerService.StreamLogs:output_type -> lazycake.v1.TaskLogLine
	10, // 14: lazycake.v1.CustomerService.ListNodes:output_type -> lazycake.v1.ListNodesResponse
	12, // 15: lazycake.v1.CustomerService.CreateGateway:output_type -> lazycake.v1.CreateGatewayResponse
	15, // 16: lazycake.v1.CustomerService.ListGateways:output_type -> lazycake.v1.ListGatewaysResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_lazycake_v1_customer_proto_init() }
func file_lazycake_v1_customer_proto_init() {
	if File_lazycake_v1_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lazycake_v1_customer_proto_rawDesc), len(file_lazycake_v1_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lazycake_v1_customer_proto_goTypes,
		DependencyIndexes: file_lazycake_v1_customer_proto_depIdxs,
		MessageInfos:      file_lazycake_v1_customer_proto_msgTypes,
	}.Build()
	File_lazycake_v1_customer_proto = out.File
	file_lazycake_v1_customer_proto_goTypes = nil
	file_lazycake_v1_customer_proto_depIdxs = nil
}
