// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: lazycake/v1/gateway.proto

package lazycakev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ByteReport carries the bytes one forwarded connection moved since its previous report
// (a delta, not a running total), so a connection that stays open for hours shows up over
// time instead of as one spike when it finally closes, and the deltas of one connection sum
// to what a single report at close used to carry. A gateway built before these fields sends
// one report at close with service unset and final unset; the coordinator treats that as the
// whole connection.
type ByteReport struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	GatewayId    string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	TaskId       string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	BytesToLocal int64                  `protobuf:"varint,3,opt,name=bytes_to_local,json=bytesToLocal,proto3" json:"bytes_to_local,omitempty"` // gateway -> local service
	BytesToTask  int64                  `protobuf:"varint,4,opt,name=bytes_to_task,json=bytesToTask,proto3" json:"bytes_to_task,omitempty"`    // local service -> gateway -> task
	Service      string                 `protobuf:"bytes,5,opt,name=service,proto3" json:"service,omitempty"`                                  // which published service the connection used
	Final        bool                   `protobuf:"varint,6,opt,name=final,proto3" json:"final,omitempty"`                                     // the connection has closed; this is its last report
	// How many connections closed since the previous report, when the gateway batches many into one. A report
	// with final set and this left at 0 (a gateway built before batching) counts as one.
	Connections   int32 `protobuf:"varint,7,opt,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByteReport) Reset() {
	*x = ByteReport{}
	mi := &file_lazycake_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByteReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByteReport) ProtoMessage() {}

func (x *ByteReport) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByteReport.ProtoReflect.Descriptor instead.
func (*ByteReport) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ByteReport) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *ByteReport) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ByteReport) GetBytesToLocal() int64 {
	if x != nil {
		return x.BytesToLocal
	}
	return 0
}

func (x *ByteReport) GetBytesToTask() int64 {
	if x != nil {
		return x.BytesToTask
	}
	return 0
}

func (x *ByteReport) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ByteReport) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

func (x *ByteReport) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

type ByteReportAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByteReportAck) Reset() {
	*x = ByteReportAck{}
	mi := &file_lazycake_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByteReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByteReportAck) ProtoMessage() {}

func (x *ByteReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_lazycake_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByteReportAck.ProtoReflect.Descriptor instead.
func (*ByteReportAck) Descriptor() ([]byte, []int) {
	return file_lazycake_v1_gateway_proto_rawDescGZIP(), []int{1}
}

var File_lazycake_v1_gateway_proto protoreflect.FileDescriptor

const file_lazycake_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x19lazycake/v1/gateway.proto\x12\vlazycake.v1\"\xe0\x01\n" +
	"\n" +
	"ByteReport\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12$\n" +
	"\x0ebytes_to_local\x18\x03 \x01(\x03R\fbytesToLocal\x12\"\n" +
	"\rbytes_to_task\x18\x04 \x01(\x03R\vbytesToTask\x12\x18\n" +
	"\aservice\x18\x05 \x01(\tR\aservice\x12\x14\n" +
	"\x05final\x18\x06 \x01(\bR\x05final\x12 \n" +
	"\vconnections\x18\a \x01(\x05R\vconnections\"\x0f\n" +
	"\rByteReportAck2T\n" +
	"\x0eGatewayService\x12B\n" +
	"\vReportBytes\x12\x17.lazycake.v1.ByteReport\x1a\x1a.lazycake.v1.ByteReportAckB:Z8github.com/mkassab215/lazycake/internal/proto/lazycakev1b\x06proto3"

var (
	file_lazycake_v1_gateway_proto_rawDescOnce sync.Once
	file_lazycake_v1_gateway_proto_rawDescData []byte
)

func file_lazycake_v1_gateway_proto_rawDescGZIP() []byte {
	file_lazycake_v1_gateway_proto_rawDescOnce.Do(func() {
		file_lazycake_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lazycake_v1_gateway_proto_rawDesc), len(file_lazycake_v1_gateway_proto_rawDesc)))
	})
	return file_lazycake_v1_gateway_proto_rawDescData
}

var file_lazycake_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lazycake_v1_gateway_proto_goTypes = []any{
	(*ByteReport)(nil),    // 0: lazycake.v1.ByteReport
	(*ByteReportAck)(nil), // 1: lazycake.v1.ByteReportAck
}
var file_lazycake_v1_gateway_proto_depIdxs = []int32{
	0, // 0: lazycake.v1.GatewayService.ReportBytes:input_type -> lazycake.v1.ByteReport
	1, // 1: lazycake.v1.GatewayService.ReportBytes:output_type -> lazycake.v1.ByteReportAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lazycake_v1_gateway_proto_init() }
func file_lazycake_v1_gateway_proto_init() {
	if File_lazycake_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lazycake_v1_gateway_proto_rawDesc), len(file_lazycake_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lazycake_v1_gateway_proto_goTypes,
		DependencyIndexes: file_lazycake_v1_gateway_proto_depIdxs,
		MessageInfos:      file_lazycake_v1_gateway_proto_msgTypes,
	}.Build()
	File_lazycake_v1_gateway_proto = out.File
	file_lazycake_v1_gateway_proto_goTypes = nil
	file_lazycake_v1_gateway_proto_depIdxs = nil
}
